source "http://rubygems.org"

gem "sinatra", :require => "sinatra/base"
gem "sinatra_more", :require => "sinatra_more/markup_plugin"
gem "i18n"
gem "haml"
gem "sass"
gem "redcarpet"
gem "nokogiri"
gem "hashie"
gem "shotgun"
